---
name: "CI"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@main"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    with:
      # FIX: Pass the exclusions into the dedicated 'platform_exclusions' parameter
      platform_exclusions: "centos-8,rocky-8,almalinux-8"
      
      # Litmus
      flags: "--shallow-clone"
    secrets: "inherit"
